### ISSUE TITLE
Followed the instructions and the following error presented on HomeBridge

### ISSUE THREAD

**Issue by ticruz98** [beele/HomebridgeLgSmartThinqAirco#16]
[2020-6-23 21:45:58] Error: spawn python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)

**Comment by beele** [comment]
Do you have pyhton3 installed?

**Comment by ticruz98** [comment]
Yes, I do. Maybe it has something to do that I'm running it on Windows 10? I've reinstalled it and this is the error I get now:

[2020-6-24 12:20:23] Error: spawn python3 ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by beele** [comment]
Windows 10 might be the issue, can you try on another os?
