### ISSUE TITLE
AC used to work on previous version but "Unsupported Protocol" Now

### ISSUE THREAD

**Issue by lowlight-orangegap** [beele/HomebridgeLgSmartThinqAirco#17]
After I connect to the LG site and paste the returned website into the terminal, I get the following error and do not get a list of my devices. (Note: This is on a Raspberry Pi)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    **response_kw)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/member/login (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 306, in <module>
    main()
  File "example.py", line 302, in main
    example(args.country, args.language, args.path, args.verbose, args.cmd, args.args)
  File "example.py", line 238, in example
    example_command(client, cmd, args)
  File "example.py", line 206, in example_command
    func(client, *args)
  File "example.py", line 32, in ls
    for device in client.devices:
  File "/usr/local/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/client.py", line 130, in devices
    self._devices = self.session.get_devices()
  File "/usr/local/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/client.py", line 121, in session
    self._session, self._devices = self.auth.start_session()
  File "/usr/local/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 380, in start_session
    self.gateway.country, self.gateway.language)
  File "/usr/local/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 276, in login
    return lgedm_post(api_root, 'member/login', data)
  File "/usr/local/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 211, in lgedm_post
    json={DATA_ROOT: data}, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='aic.lgthinq.com', port=46030): Max retries exceeded with url: /api/member/login (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1056)')))

**Comment by beele** [comment]
Seems like an ssl error (I cannot reproduce).
