### ISSUE TITLE
On / Off issues and log errors

### ISSUE THREAD

**Issue by Y8rz8** [beele/HomebridgeLgSmartThinqAirco#21]
Hi there, thanks for your plugin which finally helps me to automate AC based on temperature through SIRI shortcuts.

My 4 devices are working on HomeKit through the Home app. Everything is working as expected except that (sometimes) the device will not stop (even if the status is going from on to off in the Home app). After a few seconds the device reappears with on status.

Log hereafter  show error (at the time of changing status but also sometimes without doing nothing):

Traceback (most recent call last):
  File "example.py", line 310, in <module>

    main()
  File "example.py", line 306, in main

    example(args.country, args.language, args.path, args.verbose, args.cmd, args.args)
  File "example.py", line 219, in example

    state = json.load(f)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load

    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads

    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode

    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 221604 (char 221603)

If you can please have a look ? Any idea ?

Many thanks,
Patrice.

**Comment by beele** [comment]
Are you using the latest 0.1.4 version?

**Comment by Y8rz8** [comment]
Yes 0.1.4

**Comment by beele** [comment]
You are using 4 different AC devices?

**Comment by Y8rz8** [comment]
Yes 4 internal units // one external multi split
