### ISSUE TITLE
Unhandled promise rejection.

### ISSUE THREAD

**Issue by writingwhilenoodles** [beele/HomebridgeLgSmartThinqAirco#25]
Hi,

So the plugin sort of works, but only intermittently. About 1/3 commands work, the rest don't. It will show a change in the Homekit app but the airco itself doesn't change what it's doing.

The log shows many errors like this:

(node:391) UnhandledPromiseRejectionWarning: Error: Could not change isOn state of the AC unit!
    at LgAircoController.setPowerState (/homebridge/node_modules/homebridge-lg-airco/src/lg/lg-airco-controller.ts:45:23)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 20)

**Comment by neoworld7** [comment]
Hey
I’ve the same problem.
Rejection.

i still can control my LG airco everytime. But the state of mode of AC is false.
Put heat and the information back is that the system is cooling. 


Any solution?

![IMG_0199](https://user-images.githubusercontent.com/77917659/105626243-c580ef00-5e2e-11eb-996b-7c24725f6c26.jpeg)

**Comment by neoworld7** [comment]
Logs.
![IMG_0200](https://user-images.githubusercontent.com/77917659/105626293-fb25d800-5e2e-11eb-9dbc-87c10a2895a0.jpeg)
