### ISSUE TITLE
Errors while running python script 

### ISSUE THREAD

**Issue by seungjunProgramming** [beele/HomebridgeLgSmartThinqAirco#26]
Traceback (most recent call last):
  File "example.py", line 310, in <module>
    main()
  File "example.py", line 306, in main
    example(args.country, args.language, args.path, args.verbose, args.cmd, args.args)
  File "example.py", line 255, in example
    with open(STATE_FILE, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.homebridge/wideq_state.json'

I get this error while running the python script...
What should I do???
(I get this after pasting the redirected link)

**Comment by seungjunProgramming** [comment]
Never Mind my error....
