### ISSUE TITLE
HomeBridge and Docker Issue #2

### ISSUE THREAD

**Issue by kaiatkins** [beele/HomebridgeLgSmartThinqAirco#4]
I am using oznu/docker-homebridge with homebridge UI enabled on Western Digital PR4100

the error I am getting when home bridge loads:

[8/28/2019, 10:35:23 AM] Homebridge is running on port 53998.
Traceback (most recent call last):
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 1, in 
import wideq
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/init.py", line 3, in 
from .core import * # noqa
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in 
import requests
ModuleNotFoundError: No module named 'requests'

Here is python3 version:

/homebridge/node_modules/homebridge-lg-airco/resources/wideq # python3 --version
Python 3.7.3

When running command: python3 example.py -c “US” -l “en-US” -s "wideq_state.json" ls

/homebridge/node_modules/homebridge-lg-airco/resources/wideq # python3 example.py -c “US” -l “en-US” -s "wideq_state.json" ls
Traceback (most recent call last):
File "example.py", line 1, in 
import wideq
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/init.py", line 3, in 
from .core import * # noqa
File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in 
import requests
ModuleNotFoundError: No module named 'requests'

**Comment by beele** [comment]
I have no idea, Try the latest version I updated some stuff so it works on python 3.7.x
I've tested on rbpi3/4 and macosx

**Comment by kaiatkins** [comment]
/homebridge/node_modules/homebridge-lg-airco/resources/wideq #  python3 example.py -c “US” -l “en-US” -s "wideq_state.json" ls
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import wideq
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/__init__.py", line 3, in <module>
    from .core import *  # noqa
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by kaiatkins** [comment]
looks still same issue

**Comment by beele** [comment]
Python seems to be missing some dependencies. Is it a special kind of python installation?

**Comment by Xivi08** [comment]
Same error here. All was working perfectly until the last week.

Any idea?

**Comment by Xivi08** [comment]
Ok, solved. You need to install the "requests" module. I followed this instructions:

https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests

**Comment by beele** [comment]
Updated readme with this informatio,n! @Xivi08 
@kaiatkins does this fix the issue for you?

**Comment by kaiatkins** [comment]
Progressing :)

Now just this appears, thank you again for your help in this matter.

[1/29/2020, 11:52:45 AM] [LG-Master Bedroom] ValueError: '@AC_MAIN_WIND_STRENGTH_NATURE_W' is not a valid ACFanSpeed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 248, in <module>
    main()
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 244, in main
    example(args.country, args.language, args.state_file, args.cmd, args.args)
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 199, in example
    example_command(client, cmd, args)
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 173, in example_command
    func(client, *args)
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py", line 95, in ac_mon
    'on' if state.is_on else 'off'
  File "/homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq/ac.py", line 244, in fan_speed
    return ACFanSpeed(self.lookup_enum('WindStrength'))
  File "/usr/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: '@AC_MAIN_WIND_STRENGTH_NATURE_W' is not a valid ACFanSpeed

**Comment by beele** [comment]
@kaiatkins If you open the wideq.js file (in nano/vim/...)

Add  
`console.log(monitorLines);`
below line 118 so it should look like this:

`    const parseMon = (data) => {
        const monitorLines = data.split('; ');
        console.log(monitorLines);
        return {
            onOff: monitorLines[0],
            mode: monitorLines[1],
            currentTemp: monitorLines[2].substring(4).replace('°C', ''),
            targetTemp: monitorLines[3].substring(4).replace('°C', ''),
            speed: monitorLines[4].substring(10).replace('\n', '')
        };
    };
`

And then run it again. It should print some extra info in the logging. Could you paste that here. Might be something temperature related (like no celcius temperature available)

**Comment by kaiatkins** [comment]
I have added but don't see anything additional in logs just the Line number change wideq.js:122:42) to wideq.js:123:42)

37m[1/31/2020, 3:50:17 PM][39m Got SIGTERM, shutting down Homebridge...
[37m[1/31/2020, 3:50:25 PM][39m Loaded config.json with 1 accessories and 0 platforms.
[37m[1/31/2020, 3:50:25 PM][39m ---
[37m[1/31/2020, 3:50:25 PM][39m Loaded plugin: homebridge-lg-airco
[37m[1/31/2020, 3:50:25 PM][39m Registering accessory 'homebridge-lg-airco.HomebridgeLgAirco'
[37m[1/31/2020, 3:50:25 PM][39m ---
[37m[1/31/2020, 3:50:25 PM][39m Loaded plugin: homebridge-config-ui-x
[37m[1/31/2020, 3:50:25 PM][39m Registering platform 'homebridge-config-ui-x.config'
[37m[1/31/2020, 3:50:25 PM][39m ---
[37m[1/31/2020, 3:50:25 PM][39m Loading 0 platforms...
[37m[1/31/2020, 3:50:25 PM][39m Loading 1 accessories...
[37m[1/31/2020, 3:50:25 PM][39m [36m[LG-AirCon][39m Initializing HomebridgeLgAirco accessory...
[0;37m[1/31/2020, 3:50:25 PM] [0m[0;36m[Config][0m [0;33mHomebridge Config UI X v4.9.0 is listening on :: port 9191[0m
Path to script file: /homebridge/node_modules/homebridge-lg-airco/resources/wideq/example.py
Path to state file: /homebridge/node_modules/homebridge-lg-airco/resources/wideq/wideq_state.json

[1/31/2020, 3:50:29 PM][39m [36m[LG-AirCon][39m TypeError: Cannot read property 'substring' of undefined
    at parseMon (/homebridge/node_modules/homebridge-lg-airco/src/lg/wideq.js:123:42)
    at python.then (/homebridge/node_modules/homebridge-lg-airco/src/lg/wideq.js:25:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by piet2000** [comment]
I have the same issue. Added the extra logging and the message is :

[ 'Session expired.\n' ]

**Comment by rashmendis** [comment]
> I have the same issue. Added the extra logging and the message is :
> 
> [ 'Session expired.\n' ]

Same for me. Any fix?

**Comment by piet2000** [comment]
I fixed this. The issue is with "°C" in the example.py
remove from example.py in the lines the "°C".
'cur {0.temp_cur_c}°C; '
'cfg {0.temp_cfg_c}°C; '
then remove from /src/lg/wideq.js

        currentTemp: monitorLines[2].substring(4)**.replace('°C', '')**,
        targetTemp: monitorLines[3].substring(4)**.replace('°C', '')**,

**Comment by jakemauer** [comment]
@piet2000 Can you elaborate on your changes? I'm confused on what edits I should make or rather, what those two files should look like after I make the appropriate edits.

**Comment by beele** [comment]
I've published the new version, could you try with that? 
Please not that the config has changed! 
Follow the readme!
