### ISSUE TITLE
Setup problem 

### ISSUE THREAD

**Issue by WojtekWro** [beele/HomebridgeLgSmartThinqAirco#7]
Hi,
When I try to setup plugin following your guide I have issue. Below extract from my log.

xx@rpi3:/usr/lib/node_modules/homebridge-lg-airco/resources/wideq $ sudo python3 example.py -c "PL" -l "en-UK" -s "wideq_state.json" ls
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import wideq
  File "/usr/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/__init__.py", line 3, in <module>
    from .core import *  # noqa
  File "/usr/lib/node_modules/homebridge-lg-airco/resources/wideq/wideq/core.py", line 9, in <module>
    import requests
ImportError: No module named 'requests'_

**Comment by beele** [comment]
Run-: pip3 install requests
